name: Singularity Build
on:
  push:
    branches:
      - main

jobs:
  changes:
    name: "Changed Singularity Recipes"
    runs-on: ubuntu-latest
    outputs:
      changed_file: ${{ steps.files.outputs.added_modified }}
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

  build-test-containers:
    needs:
      - changes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        changed_file: ${{ fromJson(needs.changes.outputs.changed_file) }}
        singularity_version:
          - '4.0.1'

    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged

    name: Check ${{ matrix.changed_file }}
    steps:

      - name: Check out code for the container builds
        uses: actions/checkout@v2

      - name: Continue if Singularity Recipe
        run: |
          # Continue if we have a changed Singularity recipe
          if [[ "${{ matrix.changed_file }}" = *.def ]]; then
            echo "keepgoing=true" >> $GITHUB_ENV
          fi

      - name: Build Container
        if: ${{ env.keepgoing == 'true' }}
        env:
          recipe: ${{ matrix.changed_file }}
        run: |
         if [ -f "${{ matrix.changed_file }}" ]; then
           name=$(basename "${{ matrix.changed_file }}" ".def")
           echo "filename=${name}.sif" >> $GITHUB_ENV
           sudo -E singularity build "$name.sif" ${{ matrix.changed_file }}
         else
           echo "${{ matrix.changed_file }} is not found."
           echo "Present working directory: $PWD"
         fi

      - name: Archive Singularity Image
        if: ${{ env.name != '' }}
        uses: actions/upload-artifact@v3
        env:
          filename: ${{ env.filename }}
        with:
          name: singularity-image
          path: ${{ env.filename }}
